[package]
name = "thru"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tide = "0.16.0"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros", "sync", "time" ] }

[[example]]
name = "example"
