[package]
name = "thru"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.71"
tide = "0.16.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time" ] }

[[example]]
name = "example"
